FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

RUN npm run build

RUN npm install -g serve

EXPOSE 1002

CMD ["serve", "-s", "dist", "-l", "1002"]